#ifndef CSE2303HEADER_H_
#define CSE2303HEADER_H_
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <wait.h>
#include <signal.h>
#include <fcntl.h>
//#include <sstream>
#include <pthread.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <ctype.h>
#include <math.h>
#include <sys/time.h>
#include <sys/mman.h>
#endif /*CSE2303HEADER_H_*/
